#!/bin/bash

trap kill_processes INT

kill_processes() {
	trap '' INT TERM
	kill -TERM 0
	wait
	echo "**** Server stopped ****"
}

grunt &
php -S localhost:8080 -t ./ public/index.php &
sleep 10
open "http://localhost:8080/de/home"
echo Press Ctrl-C to stop the server.
cat
